const claw_craft = [
  {
    Tier: 1,
    Modifier: "(8–10) mana restored on hit",
    Level: 85,
    Weight: 171,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(6–7) mana restored on hit",
    Level: 80,
    Weight: 514,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(3–5) mana restored on hit",
    Level: 75,
    Weight: 1543,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(1–2) mana restored on hit",
    Level: 70,
    Weight: 7800,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(7–8)% Life Regain",
    Level: 85,
    Weight: 171,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(5–6)% Life Regain",
    Level: 80,
    Weight: 514,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "+4% Life Regain",
    Level: 75,
    Weight: 1543,
    Ember: "Vigor Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(25–29) - (30–35) added gear physical damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(19–22) - (22–26) added gear physical damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(14–17) - (17–20) added gear physical damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(11–13) - (13–15) added gear physical damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(8–10) - (11–13) added gear physical damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(7–9) - (9–11) added gear physical damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(6–7) - (7–9) added gear physical damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(5–6) - (6–7) added gear physical damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(4–5) - (5–6) added gear physical damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(47–54) - (65–74) added gear fire damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(36–41) - (49–56) added gear fire damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(27–31) - (37–43) added gear fire damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(21–24) - (29–33) added gear fire damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(17–20) - (24–28) added gear fire damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(14–17) - (20–23) added gear fire damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(12–14) - (16–19) added gear fire damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(9–11) - (14–16) added gear fire damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(7–9) - (11–13) added gear fire damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(48–55) - (64–73) added gear cold damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(36–42) - (49–56) added gear cold damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(28–32) - (37–43) added gear cold damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(22–25) - (29–33) added gear cold damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(17–20) - (23–27) added gear cold damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(14–17) - (20–23) added gear cold damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(12–14) - (16–19) added gear cold damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(11–12) - (14–16) added gear cold damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(8–10) - (11–13) added gear cold damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(6–7) - (106–121) added gear lightning damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(4–5) - (81–93) added gear lightning damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(3–4) - (62–71) added gear lightning damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(2–3) - (48–55) added gear lightning damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(1–2) - (39–45) added gear lightning damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(1–2) - (33–38) added gear lightning damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "1 - (27–31) added gear lightning damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "1 - (22–26) added gear lightning damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "1 - (19–22) added gear lightning damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "Give this gear (51–59) - (60–69) Erosion Damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "Give this gear (39–45) - (46–53) Erosion Damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "Give this gear (29–34) - (35–40) Erosion Damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "Give this gear (22–26) - (27–31) Erosion Damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "Give this gear (19–22) - (22–26) Erosion Damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "Give this gear (15–18) - (18–21) Erosion Damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "Give this gear (13–15) - (15–18) Erosion Damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "Give this gear (11–12) - (13–15) Erosion Damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "Give this gear (8–10) - (11–12) Erosion Damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "Adds (27–34) Base Wilt Damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "Adds (21–26) Base Wilt Damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "Adds (16–20) Base Wilt Damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "Adds (13–15) Base Wilt Damage",
    Level: 70,
    Weight: 2600,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "Adds (11–12) Base Wilt Damage",
    Level: 65,
    Weight: 2600,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "Adds (9–10) Base Wilt Damage",
    Level: 60,
    Weight: 2600,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "Adds Base (77–100) Shock Damage",
    Level: 85,
    Weight: 840,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "Adds Base (60–76) Shock Damage",
    Level: 80,
    Weight: 2520,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "Adds Base (46–59) Shock Damage",
    Level: 75,
    Weight: 7560,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "Adds Base (38–45) Shock Damage",
    Level: 70,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "Adds Base (32–37) Shock Damage",
    Level: 65,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "Adds Base (27–31) Shock Damage",
    Level: 60,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "Adds Base (22–26) Shock Damage",
    Level: 50,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "Adds Base (19–21) Shock Damage",
    Level: 40,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "Adds Base (15–18) Shock Damage",
    Level: 30,
    Weight: 1300,
    Ember: "Essence Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(77–100)% gear physical damage",
    Level: 85,
    Weight: 300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(60–76)% gear physical damage",
    Level: 80,
    Weight: 900,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(46–59)% gear physical damage",
    Level: 75,
    Weight: 2700,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(38–45)% gear physical damage",
    Level: 70,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(32–37)% gear physical damage",
    Level: 65,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(27–31)% gear physical damage",
    Level: 60,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(22–26)% gear physical damage",
    Level: 50,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(19–21)% gear physical damage",
    Level: 40,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(15–18)% gear physical damage",
    Level: 30,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(74–96)% Elemental damage",
    Level: 85,
    Weight: 300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(57–73)% Elemental damage",
    Level: 80,
    Weight: 900,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(44–56)% Elemental damage",
    Level: 75,
    Weight: 2700,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(37–43)% Elemental damage",
    Level: 70,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(31–36)% Elemental damage",
    Level: 65,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(26–30)% Elemental damage",
    Level: 60,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(22–25)% Elemental damage",
    Level: 50,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(18–21)% Elemental damage",
    Level: 40,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(14–17)% Elemental damage",
    Level: 30,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(74–96)% Erosion Damage",
    Level: 85,
    Weight: 300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(57–73)% Erosion Damage",
    Level: 80,
    Weight: 900,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(44–56)% Erosion Damage",
    Level: 75,
    Weight: 2700,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(37–43)% Erosion Damage",
    Level: 70,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(31–36)% Erosion Damage",
    Level: 65,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(26–30)% Erosion Damage",
    Level: 60,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(22–25)% Erosion Damage",
    Level: 50,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(18–21)% Erosion Damage",
    Level: 40,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(14–17)% Erosion Damage",
    Level: 30,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(74–96)% persistent damage",
    Level: 85,
    Weight: 300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(57–73)% persistent damage",
    Level: 80,
    Weight: 900,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(44–56)% persistent damage",
    Level: 75,
    Weight: 2700,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "(37–43)% persistent damage",
    Level: 70,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "(31–36)% persistent damage",
    Level: 65,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "(26–30)% persistent damage",
    Level: 60,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 7,
    Modifier: "(22–25)% persistent damage",
    Level: 50,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 8,
    Modifier: "(18–21)% persistent damage",
    Level: 40,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 9,
    Modifier: "(14–17)% persistent damage",
    Level: 30,
    Weight: 1300,
    Ember: "Amplified Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(34–36) - (41–44) added gear physical damage",
    Level: 85,
    Weight: 429,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: "",
    Modifier: "(3–5)% chance to cause Blinding On Hit",
    Level: "",
    Weight: "",
    Ember: "",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "(25–27) - (31–33) added gear physical damage",
    Level: 80,
    Weight: 1286,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: "",
    Modifier: "(3–5)% chance to cause Blinding On Hit",
    Level: "",
    Weight: "",
    Ember: "",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "(19–21) - (24–26) added gear physical damage",
    Level: 75,
    Weight: 3857,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: "",
    Modifier: "(3–5)% chance to cause Blinding On Hit",
    Level: "",
    Weight: "",
    Ember: "",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "1 - 5 added attack lightning damage per 12 dexterity",
    Level: 85,
    Weight: 429,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "1 - 5 added attack lightning damage per 16 dexterity",
    Level: 80,
    Weight: 1286,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "1 - 5 added attack lightning damage per 24 dexterity",
    Level: 75,
    Weight: 3857,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "2 - 4 bonus Erosion Damage as Attack Damage per 12 Intelligence",
    Level: 85,
    Weight: 429,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "2 - 4 bonus Erosion Damage as Attack Damage per 16 Intelligence",
    Level: 80,
    Weight: 1286,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "2 - 4 bonus Erosion Damage as Attack Damage per 24 Intelligence",
    Level: 75,
    Weight: 3857,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "Adds (54–69)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 85,
    Weight: 429,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier: "Adds (41–53)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 80,
    Weight: 1286,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 3,
    Modifier: "Adds (32–40)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 70,
    Weight: 3857,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 4,
    Modifier: "Adds (27–31)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 60,
    Weight: 2600,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 5,
    Modifier: "Adds (22–26)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 40,
    Weight: 2600,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 6,
    Modifier: "Adds (19–21)% of Main-hand Weapon Damage to Base Wilt Damage",
    Level: 50,
    Weight: 2600,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier:
      "Adds (3–5)% of Physical Damage of the main-hand weapon to Base Shock Damage",
    Level: 85,
    Weight: 429,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 2,
    Modifier:
      "Adds 2% of Physical Damage of the main-hand weapon to Base Shock Damage",
    Level: 80,
    Weight: 1286,
    Ember: "Ruling Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "Damage Pierces (16–24)% Elemental Resistance",
    Level: 85,
    Weight: 100,
    Ember: "Ominous Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(16–24)% additional Erosion Damage",
    Level: 85,
    Weight: 100,
    Ember: "Ominous Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(16–24)% extra damage applied to life",
    Level: 85,
    Weight: 100,
    Ember: "Ominous Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(120–180)% gear physical damage",
    Level: 85,
    Weight: 100,
    Ember: "Ominous Ember",
    Affix_Type: "Prefix",
  },
  {
    Tier: "",
    Modifier: "(3–5)% chance to cause Blinding On Hit",
    Level: "",
    Weight: "",
    Ember: "",
    Affix_Type: "Prefix",
  },
  {
    Tier: 1,
    Modifier: "(93–120) intelligence",
    Level: 85,
    Weight: 171,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(72–92) intelligence",
    Level: 80,
    Weight: 514,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(55–71) intelligence",
    Level: 75,
    Weight: 1543,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(46–54) intelligence",
    Level: 70,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 5,
    Modifier: "(38–45) intelligence",
    Level: 65,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 6,
    Modifier: "(32–37) intelligence",
    Level: 60,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 7,
    Modifier: "(27–31) intelligence",
    Level: 50,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 8,
    Modifier: "(22–26) intelligence",
    Level: 40,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 9,
    Modifier: "(17–21) intelligence",
    Level: 30,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(93–120) dexterity",
    Level: 85,
    Weight: 171,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(72–92) dexterity",
    Level: 80,
    Weight: 514,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(55–71) dexterity",
    Level: 75,
    Weight: 1543,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(46–54) dexterity",
    Level: 70,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 5,
    Modifier: "(38–45) dexterity",
    Level: 65,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 6,
    Modifier: "(32–37) dexterity",
    Level: 60,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 7,
    Modifier: "(27–31) dexterity",
    Level: 50,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 8,
    Modifier: "(22–26) dexterity",
    Level: 40,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 9,
    Modifier: "(17–21) dexterity",
    Level: 30,
    Weight: 1300,
    Ember: "Cultivation Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(24–30)% gear attack speed",
    Level: 85,
    Weight: 153,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(18–23)% gear attack speed",
    Level: 80,
    Weight: 460,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(14–17)% gear attack speed",
    Level: 75,
    Weight: 1381,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(12–13)% gear attack speed",
    Level: 70,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 5,
    Modifier: "(10–11)% gear attack speed",
    Level: 65,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 6,
    Modifier: "(8–9)% gear attack speed",
    Level: 60,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 7,
    Modifier: "+7% gear attack speed",
    Level: 50,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 8,
    Modifier: "+6% gear attack speed",
    Level: 40,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 9,
    Modifier: "+5% gear attack speed",
    Level: 30,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(31–40)% gear attack critical strike rating",
    Level: 85,
    Weight: 153,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(24–30)% gear attack critical strike rating",
    Level: 80,
    Weight: 460,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(19–23)% gear attack critical strike rating",
    Level: 75,
    Weight: 1381,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(16–18)% gear attack critical strike rating",
    Level: 70,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 5,
    Modifier: "(13–15)% gear attack critical strike rating",
    Level: 65,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 6,
    Modifier: "(11–12)% gear attack critical strike rating",
    Level: 60,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 7,
    Modifier: "(9–10)% gear attack critical strike rating",
    Level: 50,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 8,
    Modifier: "+8% gear attack critical strike rating",
    Level: 40,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 9,
    Modifier: "(6–7)% gear attack critical strike rating",
    Level: 30,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(62–80)% critical strike damage",
    Level: 85,
    Weight: 153,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(48–61)% critical strike damage",
    Level: 80,
    Weight: 460,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(37–47)% critical strike damage",
    Level: 75,
    Weight: 1381,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(31–36)% critical strike damage",
    Level: 70,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 5,
    Modifier: "(26–30)% critical strike damage",
    Level: 65,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 6,
    Modifier: "(22–25)% critical strike damage",
    Level: 60,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 7,
    Modifier: "(18–21)% critical strike damage",
    Level: 50,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 8,
    Modifier: "(15–17)% critical strike damage",
    Level: 40,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 9,
    Modifier: "(12–14)% critical strike damage",
    Level: 30,
    Weight: 1300,
    Ember: "Soulburst Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(31–40)% Wilt chance",
    Level: 85,
    Weight: 300,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(21–30)% Wilt chance",
    Level: 80,
    Weight: 900,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(11–20)% Wilt chance",
    Level: 75,
    Weight: 2700,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(1–10)% Wilt chance",
    Level: 70,
    Weight: 7800,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(16–20)% chance to gain 1 stack of Agility Blessing on defeat",
    Level: 85,
    Weight: 300,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(11–15)% chance to gain 1 stack of Agility Blessing on defeat",
    Level: 80,
    Weight: 900,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(6–10)% chance to gain 1 stack of Agility Blessing on defeat",
    Level: 75,
    Weight: 2700,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(1–5)% chance to gain 1 stack of Agility Blessing on defeat",
    Level: 70,
    Weight: 7800,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(31–40)% Shock chance",
    Level: 85,
    Weight: 300,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(21–30)% Shock chance",
    Level: 80,
    Weight: 900,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(11–20)% Shock chance",
    Level: 75,
    Weight: 2700,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(1–10)% Shock chance",
    Level: 70,
    Weight: 7800,
    Ember: "Mystery Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(25–32) Affliction inflicted per second",
    Level: 85,
    Weight: 480,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier: "(19–24) Affliction inflicted per second",
    Level: 80,
    Weight: 1440,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier: "(13–18) Affliction inflicted per second",
    Level: 70,
    Weight: 4320,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 4,
    Modifier: "(8–12) Affliction inflicted per second",
    Level: 60,
    Weight: 7800,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier:
      "Reaps 1.5 s of the DoT against enemy on Critical Strike. The effect has a 6 s cooldown against the same target",
    Level: 85,
    Weight: 480,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier:
      "Reaps 1 s of the DoT against enemy on Critical Strike. The effect has a 6 s cooldown against the same target",
    Level: 80,
    Weight: 1440,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 3,
    Modifier:
      "Reaps 0.5 s of the DoT against enemy on Critical Strike. The effect has a 6 s cooldown against the same target",
    Level: 80,
    Weight: 4320,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "+1 maximum Mobility skill Charges",
    Level: 85,
    Weight: 480,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier:
      "+20% Movement Speed, Attack Speed and Damage Avoidance for 1s after using Mobility Skills",
    Level: 85,
    Weight: 480,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 2,
    Modifier:
      "+10% Movement Speed, Attack Speed and Damage Avoidance for 1s after using Mobility Skills",
    Level: 80,
    Weight: 1440,
    Ember: "Technique Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "For every 1% attack speed, extra -0.3% return interval",
    Level: 85,
    Weight: 100,
    Ember: "Restless Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(16–24)% chance to deal double damage",
    Level: 85,
    Weight: 100,
    Ember: "Restless Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier: "(20–30)% additional Attack Damage on Low Life",
    Level: 85,
    Weight: 100,
    Ember: "Restless Ember",
    Affix_Type: "Suffix",
  },
  {
    Tier: 1,
    Modifier:
      "(-18–-14)% Elemental Resistance and Erosion Resistance for nearby enemies",
    Level: 85,
    Weight: 100,
    Ember: "Restless Ember",
    Affix_Type: "Suffix\n",
  },
];

const claw_enchant = [
  {
    Type: "Gear physical damage %",
    Effect: "(19–21)% gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Dust x20",
    Level: 20,
  },
  {
    Type: "Gear physical damage %",
    Effect: "(22–26)% gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Gear physical damage %",
    Effect: "(27–31)% gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Gear physical damage %",
    Effect: "(32–37)% gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Gear physical damage",
    Effect: "(6–7) - (7–9) added gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Dust x20",
    Level: 20,
  },
  {
    Type: "Gear physical damage",
    Effect: "(7–9) - (9–11) added gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Gear physical damage",
    Effect: "(9–11) - (11–13) added gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Gear physical damage",
    Effect: "(11–13) - (14–16) added gear physical damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added gear fire damage",
    Effect: "(12–14) - (17–20) added gear fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Dust x20",
    Level: 20,
  },
  {
    Type: "Added gear fire damage",
    Effect: "(14–17) - (21–24) added gear fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Added gear fire damage",
    Effect: "(18–21) - (25–29) added gear fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added gear fire damage",
    Effect: "(22–25) - (29–34) added gear fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added gear cold damage",
    Effect: "(13–15) - (16–19) added gear cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Dust x20",
    Level: 20,
  },
  {
    Type: "Added gear cold damage",
    Effect: "(15–18) - (20–23) added gear cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Added gear cold damage",
    Effect: "(18–21) - (24–28) added gear cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added gear cold damage",
    Effect: "(22–26) - (29–34) added gear cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added gear lightning damage",
    Effect: "1 - (29–33) added gear lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Dust x20",
    Level: 20,
  },
  {
    Type: "Added gear lightning damage",
    Effect: "(1–2) - (35–40) added gear lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Added gear lightning damage",
    Effect: "(1–2) - (42–48) added gear lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added gear lightning damage",
    Effect: "(2–3) - (50–57) added gear lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added % of physical damage as fire damage",
    Effect: "4% of physical damage added as fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added % of physical damage as fire damage",
    Effect: "5% of physical damage added as fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added % of physical damage as cold damage",
    Effect: "Added 4% of physical damage to cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added % of physical damage as cold damage",
    Effect: "Added 5% of physical damage to cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Added % of physical damage as lightning damage",
    Effect: "4% of physical damage added as lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Added % of physical damage as lightning damage",
    Effect: "5% of physical damage added as lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Elemental piercing",
    Effect: "Damage Pierces 2% Elemental Resistance",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Elemental piercing",
    Effect: "Damage Pierces 3% Elemental Resistance",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Elemental piercing",
    Effect: "Damage Pierces 5% Elemental Resistance",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Fire damage",
    Effect: "(22–25)% fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Fire damage",
    Effect: "(26–30)% fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Fire damage",
    Effect: "(31–36)% fire damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "cold damage",
    Effect: "(22–25)% cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "cold damage",
    Effect: "(26–30)% cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "cold damage",
    Effect: "(31–36)% cold damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Lightning damage",
    Effect: "(22–25)% lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Lightning damage",
    Effect: "(26–30)% lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Lightning damage",
    Effect: "(31–36)% lightning damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Erosion Damage",
    Effect: "(26–30)% Erosion Damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Erosion Damage",
    Effect: "(31–36)% Erosion Damage",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Attack block",
    Effect: "+7% attack block chance",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Attack block",
    Effect: "+8% attack block chance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 40,
  },
  {
    Type: "Attack block",
    Effect: "(9–10)% attack block chance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x6",
    Level: 50,
  },
  {
    Type: "Gear attack speed",
    Effect: "+7% gear attack speed",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Gear attack speed",
    Effect: "(8–9)% gear attack speed",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Gear attack speed",
    Effect: "(10–11)% gear attack speed",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Gear critical strike rating",
    Effect: "(9–10)% gear attack critical strike rating",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Gear critical strike rating",
    Effect: "(11–12)% gear attack critical strike rating",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Gear critical strike rating",
    Effect: "(13–15)% gear attack critical strike rating",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Attack and spell critical strike damage",
    Effect: "(18–21)% critical strike damage",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x20",
    Level: 30,
  },
  {
    Type: "Attack and spell critical strike damage",
    Effect: "(22–25)% critical strike damage",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x5",
    Level: 40,
  },
  {
    Type: "Attack and spell critical strike damage",
    Effect: "(26–30)% critical strike damage",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x10",
    Level: 50,
  },
  {
    Type: "Fire resistance",
    Effect: "(20–22)% fire resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Fire resistance",
    Effect: "(23–24)% fire resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 40,
  },
  {
    Type: "Fire resistance",
    Effect: "(25–29)% fire resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x6",
    Level: 50,
  },
  {
    Type: "Cold resistance",
    Effect: "(20–22)% cold resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Cold resistance",
    Effect: "(23–24)% cold resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 40,
  },
  {
    Type: "Cold resistance",
    Effect: "(25–29)% cold resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x6",
    Level: 50,
  },
  {
    Type: "Lightning resistance",
    Effect: "(20–22)% lightning resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Lightning resistance",
    Effect: "(23–24)% lightning resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 40,
  },
  {
    Type: "Lightning resistance",
    Effect: "(25–29)% lightning resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x6",
    Level: 50,
  },
  {
    Type: "Erosion Resistance",
    Effect: "(15–16)% Erosion Resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 40,
  },
  {
    Type: "Erosion Resistance",
    Effect: "(17–19)% Erosion Resistance",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x6",
    Level: 50,
  },
  {
    Type: "Strength",
    Effect: "(25–27) strength",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Strength",
    Effect: "(28–30) strength",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x1",
    Level: 40,
  },
  {
    Type: "Strength",
    Effect: "(31–36) strength",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 50,
  },
  {
    Type: "Dexterity",
    Effect: "(25–27) dexterity",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Dexterity",
    Effect: "(28–30) dexterity",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x1",
    Level: 40,
  },
  {
    Type: "Dexterity",
    Effect: "(31–36) dexterity",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 50,
  },
  {
    Type: "Intelligence",
    Effect: "(25–27) intelligence",
    Affix_Type: "Suffix",
    Cost: "Flame Sand x10",
    Level: 30,
  },
  {
    Type: "Intelligence",
    Effect: "(28–30) intelligence",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x1",
    Level: 40,
  },
  {
    Type: "Intelligence",
    Effect: "(31–36) intelligence",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x3",
    Level: 50,
  },
  {
    Type: "Physical Damage %; Reduced Skill Cost",
    Effect: "(20–30)% gear physical damage -5% skill cost",
    Affix_Type: "Prefix",
    Cost: "Flame Elementium x5",
    Level: 60,
  },
  {
    Type: "Chance to trigger Bloodthirst on defeat",
    Effect: "10% chance to trigger Lv. 1 Bloodthirst on defeat",
    Affix_Type: "Suffix",
    Cost: "Flame Elementium x20",
    Level: 60,
  },
];
